#!/bin/bash

result="result"
directory="md_files"
exe="/home/mohanc/bin/GOO.exe"

# We store all the ion.* files in
# directory
for dir in $directory; do

echo "------------ WELCOME ----------------"
echo "Mohan wrote this script on 10/16/12"
echo "Enter directory $dir"
cd $dir


# The pdf files will be generated by GOO.exe
# and then be put in to $result directory
if ( test -d $result ) then
	echo "Find the directory: $result"
else
	mkdir result
fi
echo "-------------------------------------"

# Make sure we carry out GOO.exe for each ion file
for md_file in `ls | grep ion`; do

  if ( test -d $md_file ) then

    echo "not doing $md_file"

  elif ( test -e $md_file ) then

#----------------------------------------------------------------------
cat > INPUT << EOF
  calculation  pdf       Extend the cell.
  geo_in_type  PROFESS   Input type of geometry file: PROFESS/VASP/QE/ABINIT/MESIA
  geo_in       $md_file 
  geo_out      ./$result/$md_file.txt 
  ssf_out      ./$result/$md_file.ssf.txt
  ntype        1         Number of different types of atoms.
  natom        128       Total number of atoms.
  pdf_dr       0.01
  pdf_rcut     10
  pdf_dg       0.01
  pdf_ng       600
EOF
#----------------------------------------------------------------------

echo "doing $md_file, PDF file in ./$result/$md_file.txt"
$exe >> ../result.txt

  fi

done

cd ..

done
